/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "core_cm3.h"

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>


#include "Scheduler.h"
#include "MY_RTOS.h"
#include "CortexMX_OS_Porting.h"

Task_ref Task1, Task2, Task3 ;

void task1(void)
{
    while(1)
    {
        /*Task1 Code*/
    }
}
void task2(void)
{
    while(1)
    {
        /*Task2 Code*/
    }
}

void task3(void)
{
    while(1)
    {
        /*Task3 Code*/
    }
}


int main(void)
{
    MYRTOS_error_ID error = NoError;
    //HW_Init (Initialize ClockTree, ResetController)
    HW_Init();
    if(MYRTOS_Init() != NoError)
        while(1);

    Task1.Stack_Size = 1024; //1kb
    Task1.p_TaskEntry = task1 ;
    Task1.Priority = 3 ;
    strcpy(Task1.TaskName,"task_1") ;

    Task2.Stack_Size = 1024; //1kb
    Task2.p_TaskEntry = task2 ;
    Task2.Priority = 3 ;
    strcpy(Task2.TaskName,"task_2") ;

    Task3.Stack_Size = 1024; //1kb
    Task3.p_TaskEntry = task3 ;
    Task3.Priority = 3 ;
    strcpy(Task3.TaskName,"task_3") ;

    error += MYRTOS_Create_Task(&Task1);
    error += MYRTOS_Create_Task(&Task2);
    error += MYRTOS_Create_Task(&Task3);

    /* Loop forever */
    while(1)
    {

    }
}
