/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_I2C_Driver.h"
#include "I2C_Slave_EEPROM.h"


void clock_init()
{
	//Enable clock for GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	//Enable clock for AFIO
	RCC_AFIO_CLK_EN();
}


int main(void)
{

	clock_init();


	//Test Case 1
	unsigned char ch1[] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	unsigned char ch2[7] = {0};

	eeprom_init();
	eeprom_write_Nbytes(0xAF, ch1, 7);   //Store 7 bytes from buffer ch1 at EEPROM Memory Address 0xAF
	eeprom_read_Nbytes(0xAF, ch2, 7);    //Read 7 bytes from EEPROM Memory Address 0xAF and store bytes in buffer ch2

	//Test Case 2
	ch1[0] = 0xA ;
	ch1[1] = 0xB ;
	ch1[2] = 0xC ;
	ch1[3] = 0xD ;

    eeprom_write_Nbytes(0XFFF, ch1, 4);	//Store 4 new bytes from buffer ch1 at EEPROM Memory Address 0XFFF
    eeprom_read_Nbytes(0XFFF, ch2, 4);  //Read 4 new bytes from EEPROM Memory Address 0XFFF and store bytes in buffer ch2



	/* Loop forever */
	while(1)
	{

	}
}

