/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x6.h"
#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32_F103C6_EXTI_Driver.h"
#include "STM32_F103C6_USART_Driver.h"
#include "STM32_F103C6_RCC_Driver.h"


void clock_init()
{
	//Enable clock for GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	//Enable clock for AFIO
	RCC_AFIO_CLK_EN();
}

uint8_t ch ;

void UART_IRQ_Callback(void)
{
	MCAL_UART_ReceiveData(USART1, (uint16_t*)&ch, disable);
	MCAL_UART_SendData(USART1, (uint16_t*)&ch, enable);

}

int main(void)
{

	UART_Config uartCFG ;

	clock_init();

	uartCFG.BaudRate = UART_BaudRate_115200 ;
	uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE ;

	uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE ;

	uartCFG.P_IRQ_Callback = UART_IRQ_Callback ;

	uartCFG.Parity = UART_Parity_NONE ;
	uartCFG.Payload_Length = UART_Payload_Length_8B ;
	uartCFG.StopBits = UART_StopBits_1 ;
	uartCFG.USART_Mode = UART_Mode_TX_RX ;

	MCAL_UART_Init(USART1, &uartCFG) ;
	MCAL_UART_GPIO_Set_pins(USART1);



	while(1)
	{

	}
}

