/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6_GPIO_Driver.h"
#include "STM32F103x6.h"
#include "lcd_driver.h"
#include "Keypad_Driver.h"

#define ZERO 				0x01
#define ONE 				0x79
#define TWO 				0x24
#define THREE 				0x30
#define FOUR 				0x4C
#define FIVE 				0x12
#define SIX 				0x02
#define SEVEN 				0x19
#define EIGHT 				0x00
#define NINE 				0x10


GPIO_PinConfig_t PinCfg ;

void clock_init()
{
	//enable clock GPIOA
	RCC_GPIOA_CLK_EN() ;
	//enable clock GPIOB
	RCC_GPIOB_CLK_EN() ;
}

void GPIO_init()
{
	//GPIOB Pin 9~15 output with speed 10MHZ for Seven Segment

	PinCfg.GPIO_PinNumber = GPIO_PIN_9 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_10 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_11 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_12 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_13 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_14 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_15 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP ;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_Init(GPIOB,&PinCfg);
}

void my_wait(int x)
{
	unsigned int i , j;
	for(i = 0; i < x ; i++)
		for(j = 0; j < 255 ;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	LCD_INIT();
	LCD_WRITE_STRING("Hey there");
	my_wait(500);
	LCD_clear_screen();
	unsigned char pressed_key;
	unsigned char seg[] = {ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,ZERO} ;
	unsigned char lcd[] = {'0','1','2','3','4','5','6','7','8','9','0'} ;
	for(unsigned int i = 0 ; i<11 ; i++)
	{
		MCAL_GPIO_WritePort(GPIOB, seg[i] << 9);
		LCD_WRITE_CHAR(lcd[i]);
		my_wait(1000); // 1 sec delay
	};
	LCD_clear_screen();
	KEYPAD_INIT();
	LCD_WRITE_STRING("Keypad is ready");
	my_wait(500);
	LCD_clear_screen();

	while(1)
	{
		pressed_key = KEYPAD_GETCHAR();
		switch(pressed_key)
		{
		case ('!'):
						LCD_clear_screen();
		break;
		case ('N'):
						break;
		default:
			LCD_WRITE_CHAR(pressed_key);
			break;
		}

		//PA1 >>> connected to external PUR (default: 1)
		//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // press
		//		{
		//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
		//			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); // Single press
		//		}
		//
		//		//PA13 >>> connected to external PDR (default: 0)
		//		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) // multi pressing
		//		{
		//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		//
		//		}
		//		my_wait(1);
	}
}

